### PR TITLE
Fix for width bug.

### PR DESCRIPTION
**Pull request by Gremlyn**
When using this.element.width(), you get an integer stripped of it's qualifier (px, %, em). This works fine when all elements are shown, though I'm not positive why (maybe CSS computes and returns a pixel width when it knows one?), but if you pass it 100% and then set the width, it gets understood as '100px' instead of '100%'. Switching over to this.element.css('width') returns the fully qualified width and sets properly even when an item is hidden and only known as 100% of something.

### CODE REVIEW

**Comment by bseth99** [comment]
This seems to work.  Its odd because I was [researching it yesterday](http://stackoverflow.com/questions/3557718/detecting-width-auto-in-jquery) and it led me to believe that the solution you proposed here would not work.  But [subsequent testing](http://jsfiddle.net/bseth99/6XsTy/) appears to debunk that original thinking.  Based on that, your change seems to solve the problem.  The only other thought I had was perhaps it makes more sense to move this logic into the <code>_init()</code> function such that it enables resizing the widget with a call to <code>$(...).labeledslider()</code>.  Could you make that change and I'll pull all of it in?  Thanks.

**Comment by Gremlyn** [comment]
Sure, give me a day or two to get it together.

**Comment by Gremlyn** [comment]
Just doing a little testing with the resize code in the init function. It doesn't quite work how I might have hoped. Since The width is set on the parent of the initially created div, it's really not feasible to change the width (or height) of one div and not the other, else you end up with something that looks completely wrong.

If you then change the width of both divs through whatever chosen method, resetting the width through the _init function becomes unnecessary since you've already done it. Unless I'm missing something in what you're asking, I think resizing in the way you suggest won't have any useful impact on the widget.

**Comment by bseth99** [comment]
Ok, I'll pull in what you've done and double check my thinking.  You might be right, it may have no value.  Thanks

**Pull request merged**
